# # SaaS版
# engines:
#   # ... CONFIG CONTENT ...
#   tslint:
#     enabled: true
#     # ... CONFIG CONTENT ...
#     checks:
#       comment-format:
#         enabled: false
#       whitespace:
#         enabled: false
#       semicolon:
#         enabled: false
#       no-console:
#         enabled: false
# # ... CONFIG CONTENT ...
---
# https://docs.codeclimate.com/docs/advanced-configuration
version: "2"
checks:
  # commenct is default
#   argument-count:
#     config:
#       threshold: 4
#   complex-logic:
#     config:
#       threshold: 4
#   file-lines:
#     config:
#       threshold: 250
#   method-complexity:
#     config:
#       threshold: 5
#   method-count:
#     config:
#       threshold: 20
#   method-lines:
#     config:
#       threshold: 25
#   nested-control-flow:
#     config:
#       threshold: 4
#   return-statements:
#     config:
#       threshold: 4
#   similar-code:
#     config:
#       threshold: # language-specific defaults. an override will affect all languages.
#   identical-code:
#     config:
#       threshold: # language-specific defaults. an override will affect all languages.
plugins:
  # https://docs.codeclimate.com/docs/list-of-engines
  # coffeelint:
  #   enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      # https://docs.codeclimate.com/docs/duplication
      languages:
        - typescript
        # - ruby
        - javascript
        # - python
        # - php
  eslint:
    # https://docs.codeclimate.com/docs/eslint
    enabled: true
    channel: "stable"
    # config: .eslintrc.json
  fixme:
    enabled: true
  #rubocop:
  #  enabled: true
  ##
  ## Community-Supported Plugins
  ##
  markdownlint:
    enabled: true
  # semgrep:
    # enabled: true
  # tslint:
    # https://docs.codeclimate.com/docs/tslint
    # $  ./node_modules/.bin/tslint src/**/*.ts
    #  enabled: true
    #  config: tslint.json
exclude_patterns:
  # https://docs.codeclimate.com/docs/excluding-files-and-folders#section-auto-generated-file-and-folder-exclusions
  - config/
  - db/
  - dist/
  - features/
  - "**/node_modules/"
  - script/
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - Tests/
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  # add
  - "**/*.min.js"
  - "**/*.min.css"
  - "**/__tests__/"
  - "**/__mocks__/"
