---
services:
  chatgpt:
    image: ${CI_REGISTRY_IMAGE:-gitlab.example.com/user/chatgpt-mattermost-bot}:${CI_COMMIT_REF_NAME:-local}
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV:-production}
    restart: always
    cap_drop:
      - ALL
    env_file: .env # Dockerfileでも有効にするために必須
    # .envファイルより環境変数を有効にする場合
    # environment:
    #   CONFIG_FILE: ./config.yaml
    #   DEBUG_LEVEL: ${DEBUG_LEVEL}
    #   DEBUG_JSON: ${DEBUG_JSON}
    #   DEBUG_COLORS: ${DEBUG_COLORS}
    volumes:
      - ./config.yaml:/app/config.yaml
