---
services:
  chatbot:
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
    build: .
    restart: always
    environment:
      MATTERMOST_URL: ${MATTERMOST_URL}
      MATTERMOST_TOKEN: ${MATTERMOST_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AZURE_OPENAI_API_KEY: ${AZURE_OPENAI_API_KEY}
      AZURE_OPENAI_API_INSTANCE_NAME: ${AZURE_OPENAI_API_INSTANCE_NAME}
      AZURE_OPENAI_API_DEPLOYMENT_NAME: ${AZURE_OPENAI_API_DEPLOYMENT_NAME}
      AZURE_OPENAI_API_VERSION: ${AZURE_OPENAI_API_VERSION}
      DEBUG_LEVEL: ${DEBUG_LEVEL}
      DEBUG_JSON: ${DEBUG_JSON}
      DEBUG_COLORS: ${DEBUG_COLORS}
