image:
  registry: ghcr.io/yguy
  repository: chatgpt-mattermost-bot
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []

replicaCount: 1

nameOverride: ""
fullnameOverride: "chatgpt-mattermost-bot"

config:                   #   required:   example:                    description:
  MATTERMOST_URL: ""      #	  yes	        https://mattermost.server	  The URL to the server. This is used for connecting the bot to the Mattermost API
  MATTERMOST_TOKEN: ""	  #   yes	        abababacdcdcd	              The authentication token from the logged in mattermost bot
  OPENAI_API_KEY: ""	    #   yes	        sk-234234234234234234	      The OpenAI API key to authenticate with OpenAI
  OPENAI_MODEL_NAME: ""	  #   no	        gpt-3.5-turbo	              The OpenAI language model to use, defaults to gpt-3.5-turbo
  OPENAI_MAX_TOKENS: ""	  #   no	        2000	                      The maximum number of tokens to pass to the OpenAI API, defaults to 2000
  OPENAI_TEMPERATURE: ""  #   no	        0.2	                        The sampling temperature to use, between 0 and 2, defaults to 1. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.
  YFILES_SERVER_URL: ""	  #   no	        http://localhost:3835	      The URL to the yFiles graph service for embedding auto-generated diagrams.
  NODE_EXTRA_CA_CERTS: "" #   no	        /file/to/cert.crt	          a link to a certificate file to pass to node.js for authenticating self-signed certificates
  MATTERMOST_BOTNAME: ""  #   no	        "@chatgpt"	                the name of the bot user in Mattermost, defaults to '@chatgpt'
  PLUGINS: ""             #   no	        graph-plugin, image-plugin	The enabled plugins of the bot. By default, all plugins (grpah-plugin and image-plugin) are enabled.
  DEBUG_LEVEL: ""         #   no	        TRACE	                      a debug level used for logging activity, defaults to INFO
  BOT_CONTEXT_MSG: ""     #   no	        15	                        The number of previous messages which are appended to the conversation with ChatGPT, defaults to 100
  NODE_ENV: ""            #   no          development                 The mode NodeJS runs in. Defaults to production
  BOT_INSTRUCTION: ""     #   no          Act like Elon Musk          Extra instruction to give your assistance. How should the assistant behave?


serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10002

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10002
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
