apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatgpt-mattermost-bot.fullname" . }}-secret
  labels:
    app: chatgpt-mattermost-bot
  {{- include "chatgpt-mattermost-bot.labels" . | nindent 4 }}
stringData:
  MATTERMOST_TOKEN: "{{ required "MATTERMOST_TOKEN is required" .Values.config.MATTERMOST_TOKEN }}"
  OPENAI_API_KEY: "{{ required "OPENAI_API_KEY is required" .Values.config.OPENAI_API_KEY }}"